In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier


In [ ]:
df=pd.read_csv('/content/data.csv')
df

name  gives_birth  aquatic_animal  aerial_animal  has_legs  \
0       human            1               0              0         1   
1      python            0               0              0         0   
2      salmon            0               1              0         0   
3        frog            0               2              0         1   
4         bat            1               0              1         1   
5      pigeon            0               0              1         1   
6         cat            1               0              0         1   
7       shark            1               1              0         0   
8      turtle            0               2              0         1   
9  salamander            0               2              0         1   

  class_label  
0      mammal  
1     reptile  
2        fish  
3   ampbibian  
4        bird  
5        bird  
6      mammal  
7        fish  
8   amphibian  
9   amphibian

In [ ]:
x=df[['gives_birth','aquatic_animal','aerial_animal','has_legs']]
y=df[['class_label']]

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.3)
print(x_test)
print(y_test)

   gives_birth  aquatic_animal  aerial_animal  has_legs
6            1               0              0         1
4            1               0              1         1
1            0               0              0         0
  class_label
6      mammal
4        bird
1     reptile


In [ ]:
kn=KNeighborsClassifier(n_neighbors=1)
kn.fit(x_train,y_train.values.ravel())
y_pred = kn.predict(x_test)
print(y_pred)

['mammal' 'bird' 'fish']


In [ ]:
from sklearn.metrics import classification_report,confusion_matrix

In [ ]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[1 0 0 0]
 [0 0 0 0]
 [0 0 1 0]
 [0 1 0 0]]
              precision    recall  f1-score   support

        bird       1.00      1.00      1.00         1
        fish       0.00      0.00      0.00         0
      mammal       1.00      1.00      1.00         1
     reptile       0.00      0.00      0.00         1

    accuracy                           0.67         3
   macro avg       0.50      0.50      0.50         3
weighted avg       0.67      0.67      0.67         3



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1

In [ ]:
print(kn.predict(x_train))
print(y_train.values.ravel())

['ampbibian' 'bird' 'ampbibian' 'mammal' 'fish' 'ampbibian' 'fish']
['ampbibian' 'bird' 'amphibian' 'mammal' 'fish' 'amphibian' 'fish']
