In [26]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

In [27]:
df=pd.read_csv('/content/Advertising.csv')
df
df.head()

Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [28]:
x=df.drop(['Sales'],axis=1).values

In [29]:
y=df['Sales'].values

In [30]:
print(x)

[[  1.  230.1  37.8  69.2]
 [  2.   44.5  39.3  45.1]
 [  3.   17.2  45.9  69.3]
 [  4.  151.5  41.3  58.5]
 [  5.  180.8  10.8  58.4]
 [  6.    8.7  48.9  75. ]
 [  7.   57.5  32.8  23.5]
 [  8.  120.2  19.6  11.6]
 [  9.    8.6   2.1   1. ]
 [ 10.  199.8   2.6  21.2]
 [ 11.   66.1   5.8  24.2]
 [ 12.  214.7  24.    4. ]
 [ 13.   23.8  35.1  65.9]
 [ 14.   97.5   7.6   7.2]
 [ 15.  204.1  32.9  46. ]
 [ 16.  195.4  47.7  52.9]
 [ 17.   67.8  36.6 114. ]
 [ 18.  281.4  39.6  55.8]
 [ 19.   69.2  20.5  18.3]
 [ 20.  147.3  23.9  19.1]
 [ 21.  218.4  27.7  53.4]
 [ 22.  237.4   5.1  23.5]
 [ 23.   13.2  15.9  49.6]
 [ 24.  228.3  16.9  26.2]
 [ 25.   62.3  12.6  18.3]
 [ 26.  262.9   3.5  19.5]
 [ 27.  142.9  29.3  12.6]
 [ 28.  240.1  16.7  22.9]
 [ 29.  248.8  27.1  22.9]
 [ 30.   70.6  16.   40.8]
 [ 31.  292.9  28.3  43.2]
 [ 32.  112.9  17.4  38.6]
 [ 33.   97.2   1.5  30. ]
 [ 34.  265.6  20.    0.3]
 [ 35.   95.7   1.4   7.4]
 [ 36.  290.7   4.1   8.5]
 [ 37.  266.9  43.8   5. ]
 

In [31]:
print(y)

[22.1 10.4  9.3 18.5 12.9  7.2 11.8 13.2  4.8 10.6  8.6 17.4  9.2  9.7
 19.  22.4 12.5 24.4 11.3 14.6 18.  12.5  5.6 15.5  9.7 12.  15.  15.9
 18.9 10.5 21.4 11.9  9.6 17.4  9.5 12.8 25.4 14.7 10.1 21.5 16.6 17.1
 20.7 12.9  8.5 14.9 10.6 23.2 14.8  9.7 11.4 10.7 22.6 21.2 20.2 23.7
  5.5 13.2 23.8 18.4  8.1 24.2 15.7 14.  18.   9.3  9.5 13.4 18.9 22.3
 18.3 12.4  8.8 11.  17.   8.7  6.9 14.2  5.3 11.  11.8 12.3 11.3 13.6
 21.7 15.2 12.  16.  12.9 16.7 11.2  7.3 19.4 22.2 11.5 16.9 11.7 15.5
 25.4 17.2 11.7 23.8 14.8 14.7 20.7 19.2  7.2  8.7  5.3 19.8 13.4 21.8
 14.1 15.9 14.6 12.6 12.2  9.4 15.9  6.6 15.5  7.  11.6 15.2 19.7 10.6
  6.6  8.8 24.7  9.7  1.6 12.7  5.7 19.6 10.8 11.6  9.5 20.8  9.6 20.7
 10.9 19.2 20.1 10.4 11.4 10.3 13.2 25.4 10.9 10.1 16.1 11.6 16.6 19.
 15.6  3.2 15.3 10.1  7.3 12.9 14.4 13.3 14.9 18.  11.9 11.9  8.  12.2
 17.1 15.   8.4 14.5  7.6 11.7 11.5 27.  20.2 11.7 11.8 12.6 10.5 12.2
  8.7 26.2 17.6 22.6 10.3 17.3 15.9  6.7 10.8  9.9  5.9 19.6 17.3  7.6
  9.7 1

In [32]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [33]:
from sklearn.linear_model import LinearRegression
m1=LinearRegression()
m1.fit(x_train,y_train)
y_pred=m1.predict(x_test)
print(y_pred)

[16.02320967 20.75091247  8.23172465 23.18015434 21.78136742 14.9919009
  9.7625097  14.85711037 20.79821513  9.84494555 21.73920746 19.0929665
  3.39131264 10.40481891 16.74487369 12.02961464 16.6324654  15.15664468
 13.19849987 19.50666943 10.53938979 21.13701039 22.89762992 14.10435257
 11.54050129  9.60871738 15.10648135 20.65780667 15.75777601 19.86678561
  9.55265587  8.23397501  7.5933618  18.08215768  5.63836332 19.74820547
 10.94324771 15.40861065 16.84528541  9.88649272 24.12631853 15.31719759
 11.88758325  6.44920429  4.33335801  5.92475364  9.96724313 17.2455181
  8.88784596 17.15231878  6.32044801 12.6465427  11.64034676 15.31066458
 13.30678097 23.65010703 16.34935573 10.54018983 21.17221326 15.44477027]


In [34]:
m1.predict([[1.0, 230.1,  37.8 , 69.2]])

array([20.53832315])

In [35]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)


0.9131999598676157

In [36]:
plt.figure(figsize=(15,10))
plt.scatter(y_test,y_pred)
plt.title("Actual vs Predicted")
plt.xlabel("Actual")
plt.ylabel("predicted")

Text(0, 0.5, 'predicted')